IdentityPython/pyFF

- src/pyff/builtins.py
Backwards incompatible change that will now accept configured strings verbatim, unless they're prefixed with the string `prefix` (allowing for whitespace around that) which would trigger the previous behaviour of adding a datetime-based string at the end.
A fix for the recent (well, Nov 2014) breakage in FEIDE, cf. the "Change on eduGAIN's metadata ID" thread on the eduGAIN TSG list.
> Change EntitiesDescriptor/@ID generation behaviour

- src/pyff/xslt/regauth.xsl
Copy an existing `registrationAuthority` value into an Entity Attribute (of configurable value) in the same EntityDescriptor, allowing simpler filtering based on registrar by metadata consumers. Makes installation of https://github.com/ukf/mdrpi-match-idp-ext (Shibboleth IDP v2 extension to process `registrationAuthority`) at the metadata consumer unnecessary, at the cost of slightly bloating the EntityDescriptor (redundant information).
Usage:
```yaml
- xslt:
stylesheet: regauth.xsl
#entityAttribute: http://example.org/attributes/registrationAuthority
```
The default is to use the Entity Attribute defined by DFN-AAI to specifically express `registrationAuthority` (`http://aai.dfn.de/edugain/registrationAuthority`) but this can easily be replaced with a value of your own chosing …
> XSLT that copies mdrpi:RegistrationInfo/@registrationAuthority to an EA

- src/pyff/constants.py
Not sure for what this xmlns declaration is needed, but I found this broken URI in some generated SAML. FWIW, there wasn't even an XML element using that namespace in the document.
> Looks like a botched URI for the pyff namespace constant?

- setup.py
I created a Docker container, installing pyFF from PyPI using `pip` into it. pyFF happened to be installed under CPython 3.4. However, pyFF 0.9.4 is syntactically incompatible with CPython 3, and thus the installed `pyff` executable was unusable. Depending on circumstances, it may take some time to rebuild such a container. Furthermore, in this case, installing PyFF 0.9.4 appears to still require a dual Python 2 and Python 3 installation in a container image intended to be minimal in size. The ideal solution is to complete Python 3 support. For now, here is a pull request that improves `setup.py` to ‘fail early’ in case of invocation under an unsupported platform according the documentation.
@leifj, please review for merging.
> Patch to improve setup.py w.r.t. robustness across platforms

- src/pyff/site/static/js/jquery-ds-widget.js
Fixes issue 142 'Cannot remove a previously selected IdP from discovery'
by fixing an error in the _update method of the discovery_client widget
defined in the file jquery-ds-widget.js. The error was simply the wrong
CSS class assigned as the selector in a call to .on() to bind the click
event.
* [X ] Does your submission pass tests?
> Fix for issue 142 'Cannot remove a previously selected IdP...'

- src/pyff/site/static/js/jquery-ds-widget.js
When displaying search results do not render a blank icon. Instead use a
slightly different template that renders with the div containing the
icon having style="visibility: hidden".
Note that a side effect of having two templates and the selection determined by whether the data about the IdP has an 'entity_icon' or not is that for IdPs that do not have any logos in metadata the "preferrred method" display also looks cleaner.
* [ X] Does your submission pass tests?
> Do not render blank icon for search results

- src/pyff/mdx.py
The pyffd executable takes as a command line option --frequency but
without this fix it has no effect since the code parsing the command
line incorrectly sets the attribute on the config object.
* [ X] Does your submission pass tests?
> Fix processing of --frequency option for pyffd executable

- src/pyff/samlmd.py
Sometime eduGAIN favicons throw 404, 403 or other funny things and we get an exception that confuses pyff -- just ignore this stuff and rely on the checks already in place.
> discojson: don't die if favicon unreachable

- src/pyff/parse.py
- src/pyff/samlmd.py
Avoid spaghetti code among parse.py and samlmd.py .
> Have all parsers in parse.py -- fixes #147

- src/pyff/site/static/js/ds-client.js
The item object passed around includes an entity property, and that
entity property is itself an object that some templates expect to
contain properties entity_id and entity_icon. This commit moves code for
cleaning the item and making sure there are properties entity_id and
entity_icon into a function.
It also applies that function in the logic branch executed when the
cache_time has expired. This fixes an issue where the ra21.html template
expects entity_id and entity_icon and when they are not present due to
the cache expiring the discovery service stops working.
* [X ] Have you …
> Fix cleaning of item object

- src/pyff/site/static/js/jquery-ds-widget.js
Fix so that when clicking to remove a rendered element or entity
the correct number of entities rendered is passed to the _after()
function, which then passes the correct number to the defined (if any)
after() function. Without this change the _after() function is always
passed -1 and therefore after() is always passed -1.
> Call after function with number rendered after remove

- src/pyff/mdq.py
This change fixes the following error while compiling bytecode:
File "/usr/lib/python2.7/site-packages/pyff/mdq.py", line 48
from .logs import get_log
SyntaxError: from __future__ imports must occur at the beginning of the file
I'm not a python expert, there may be a better correction.
> fix __future__ import

- setup.py
The first commit adds an explicit dependency on python3, as well as classifiers for pipy.
The second commit get rid of a legacy dependency on futures, useless with python 3, and harmful for people installing software using native packaging system instead of using pip.
> More explicit  dependency on python 3

- src/pyff/api.py
Since the start_date passed into the
apscheduler.triggers.interval.IntervalTrigger instances is explicitly
using UTC the timezone argument needs to be passed with UTC as a value.
Since apscheduler only supports pytz and not datetime.timezone we pass
in timezone=pytz.utc.
* [ X] Have you added an explanation of what problem you are trying to solve with this PR?
* [ X] Have you added information on what your changes do and why you chose this as your solution?
It is not clear there exists any test harness for the scheduler yet.
* [X ] Does your submission pass tests?
The same tests pass before and after this change (there are currently 8 failing on master and the 1.1.1 tag).
The …
> Add timezone argument for IntervalTrigger

- src/pyff/api.py
Add logic to lowercase the query text or match string for the
process_handler to make its behavior consistent with the API
search_handler so that a frontend can point at either search URL and
observe the same case behavior.
* [X ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
There does not appear to be a test harness yet for testing the process_handler.
* [ X] Does your submission pass tests?
The same tests pass before and after the change.
The current code base is not following PEP8 at this time.
> Lowercase query match string for process_handler

- src/pyff/store.py
When Redis is used as the job store the unpickling of an instance of
RedisWhooshStore throws an AttributeError because self._redis does not
exist when the test to see if self._redis is None is executed. This
patch assigns self._redis to getattr(self, '_redis', None) before the
test and prevents the AttributeError exception from being thrown.
* [X ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
There does not appear to be a test harness for APScheduler jobs.
Current tests fail but the failures appear to not be related to this patch.
* [ X] …
> Prevent error when unpickling RedisWhooshStore from Redis

- src/pyff/utils.py
Use the pop() methods for the LRUCache and redis-collections Dict
classes instead of del to prevent IndexError when the key is missing.
> Better __delitem__ for LRUProxyDict to prevent IndexError

- src/pyff/store.py
This patch fixes the incorrect search behaviour on searches containing spaces. Thx to @c00kiemon5ter for showing the way!
> Fix issue #156

- src/pyff/constants.py
I have not used this myself yet but the code for `PYFF_` environment variables does not quite match the inline documentation which states that:
> Any occurence of '.' or '-' is also transscribed to '_' when the setting is referenced as an environment variable
But so far only dots were replaced but not (also) dashes. This PR also replaces dashes with underscores.
> Replace dash with underscore when matching envvars

- src/pyff/xslt/tidy.xsl
In order to avoid failing XSD schema validation at metadata consumers configured to perform validation, should an entity reference WS-* XSD schemas within (non-SAML) md:RoleDescriptor element but the metadata consumer is lacking a copy of the relevant XSD schema files.
As someone explained on the REFEDS FOG list:
> The reason for this rather harsh treatment is that RoleDescriptor is
> one of the very few places in the SAML schema which doesn't allow
> for lax validation. That means that if you republish this construct
> to your customers, if ANY of them schema-validate, that validation
> will fail unless they have the specific schema available.
This was also discussed on the [edugain-discuss](https://lists.geant.org/sympa/arc/edugain-discuss/2014-11/msg00031.html) [mailing …
> Remove md:RoleDescriptor elements

- README.rst
Let's promote the official project homepage, instead of multiple
heterogenous and sometimes obsoletes URLs.
> Better reference to online resources

- src/pyff/utils.py
Fix to pass the redis_host and redis_port to the apscheduler
RedisJobStore() instantiation.
* [X ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
> Add Redis host and port to RedisJobStore

- docs/usage/running.rst
- examples/edugain-copy.fd
- examples/edugain-mdq.fd
- examples/eidas.fd
- examples/mdx.fd
- examples/met.mdx
- examples/ndn.fd
- examples/new-renater.fd
- examples/test.fd
Update documentation and examples so that content negotiation
using the "when accept" builtin demonstrates how to configure
the pyFF wsgi app to accept the application/samlmetadata+xml
content type as required by the SAML MDQ specification, but also accept
application/xml so that the service is generous with what it accepts
since not all MDQ clients are compliant. Also change the emit pipe value
to application/samlmetadata+xml so that the documentation helps leads
deployers to configurations that deliver a compliant MDQ service.
* [X ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X ] Have you added information on what your changes do …
> Update documentation and examples for content negotiation

- src/pyff/utils.py
Importing DFN metadata for EduGAIN fails because the provided XML
document triggers a huge input lookup:
Error parsing http://www.aai.dfn.de/fileadmin/metadata/dfn-aai-edugain+idp-metadata.xml: internal error: Huge input lookup
As metadata can be large quite frequently it seems sensible to enable
this option by default.
> Enable huge_tree option for parse_xml

- src/pyff/api.py
- src/pyff/constants.py
If no Accept header is present or it is one of the wildcards
application/*, text/*, or */* then inspect the request path for
an extension for a hint on what format (e.g., XML or JSON) to return,
but do not inspect the path for an extension when an Accept header
is present and not one of the wildcards.
> Only use path extension when no Accept header is present

- src/pyff/site/static/css/icon.css
It's a simple CSS line change to prevent logos from distortion. According to the [204 issue](https://github.com/IdentityPython/pyFF/issues/204).
> distorted logo fix, issue 204

- requirements.txt
- setup.py
- test_requirements.txt
At least the pyXMLSecurity requirement was not present in requirements.txt. Better use the text-files as the canonical source, and load them in setup.py like README.rst and NEWS.txt is loaded.
Using pathlib should be a cross-platform way of dealing with paths and filenames.
Also, I believe python_requires should be passed to setup() and not just declared in setup.py.
> improve portability and remove redundant set of requirements

- Makefile
If acceptable, please apply this PR and run 'make reformat' and commit the results.
A convenience is to install isort, black and mypy using pipx to have them available everywhere.
To handle different output from different versions of these tools (when developer's installed versions might vary), an idea might be to specify exact versions of them in test_requirements.txt. The ones we currently use in eduID are:
black==19.10b0
isort==5.6.4
> Add makefile with a 'reformat' target to reformat the project using black (and isort).

- src/pyff/api.py
- src/pyff/builtins.py
- src/pyff/locks.py
- src/pyff/resource.py
- src/pyff/utils.py
> minor fixes

- requirements.txt
- src/pyff/api.py
- src/pyff/builtins.py
- src/pyff/parse.py
- src/pyff/pipes.py
- src/pyff/resource.py
- src/pyff/samlmd.py
- src/pyff/test/test_md_api.py
- src/pyff/test/test_pipeline.py
- src/pyff/utils.py
Writing a test case for the /api/resources endpoint revealed that the timestamps were not time zone aware. Looking deeper into it, it seemed like pyFF could use ISO8601 parsing/formatting capabilities available in Python3 and remove an external dependency.
Added typing annotations as I went looking through the code.
> time handling fixes

- src/pyff/builtins.py
- src/pyff/pipes.py
This is an attempt to make the pipe decorator a bit more typesafe based on a discussion with @fredrikt
> a @pipe decorator that maps opts to pydantic data classes on the fly

- src/pyff/api.py
- src/pyff/constants.py
- src/pyff/resource.py
- src/pyff/test/test_md_api.py
This is about making a local backup copy of metadata files that parses so we can use it as fallback if something happens to the original URL. Makes pyFF more resilient to network failures etc.
> add support for saving and falling back to a local backup copy of metadata streams

- .travis.yml
- Makefile
- requirements.txt
- setup.py
- src/pyff/logs.py
- src/pyff/test/test_md_api.py
- src/pyff/test/test_pipeline.py
- test_requirements.txt
In the process, I've changed a lot of test cases in test_pipeline to not needlessly capture stdout/err/logging,
> use pytest, since nosetests isn't maintained anymore.

- pytest.ini
- setup.py
- src/pyff/api.py
- src/pyff/builtins.py
- src/pyff/constants.py
- src/pyff/decorators.py
- src/pyff/fetch.py
- src/pyff/md.py
- src/pyff/mdq.py
- src/pyff/parse.py
- src/pyff/pipes.py
- src/pyff/repo.py
- src/pyff/resource.py
- src/pyff/samlmd.py
- src/pyff/store.py
- src/pyff/test/__init__.py
- src/pyff/test/test_store.py
- src/pyff/test/test_utils.py
- src/pyff/tools.py
- src/pyff/utils.py
- src/pyff/wsgi.py
use absolute imports and clean out unused imports
> imports cleanup

- requirements.txt
- src/pyff/builtins.py
- src/pyff/store.py
ipaddr library has been superseded by ipaddress from standard library:
https://github.com/google/ipaddr-py
> Switch to ipaddress

- src/pyff/builtins.py
Replace split() / startswith() strategy with regular expression search that anchors on a word boundary.
This is a suggested fix for https://github.com/IdentityPython/pyFF/issues/231
Being unaware of requirements that were used for the prior implementation, I'm using a search pattern that anchors the match on the beginning of a word boundary (/b) with the assumption that the user interface shouldn't get all matches, but rather just those where the query string starts with a letters at the beginning of a word.
Using this regular expression seems like the most straightforward approach. I haven't performed any comparative timing between it, and iterating over the split() / lower().startswith() code it replaces. In my unscientific tests, the search results are returned quickly enough.
> Allow multi-word search query strings

- src/pyff/api.py
Currently caching of GET requests only considers the url path.
This PR changes the cache key to also contain the query string.
Reason:
I am using thiss-js as identity selector, which submits GET requests with the search string as a query string parameter:
E.g.:
`curl 'https://bach-id-mdq.wu.ac.at/entities/?q=wirtschaftsuni' -H 'Accept: application/json'`
`curl 'https://bach-id-mdq.wu.ac.at/entities/?q=tuwien' -H 'Accept: application/json'`
Without considering the query string, the first request will be cached and the second will request will return a wrong result.
Cheers,
--leo
> respect querystring when caching GET requests

- src/pyff/repo.py
Since Python 3.11 the seed given to the `random.seed()` function must be one of the following types: NoneType, int, float, str, bytes, or bytearray.
Reference: https://docs.python.org/3.11/library/random.html#random.seed
When using `self` as the seed, the random part is the memory address of the object, which is equivalent to its identity. Using the identity (an int) should have the same effect in terms of entropy.
> Fix type of seed to the random number generator

- requirements.txt
- src/pyff/api.py
- src/pyff/builtins.py
- src/pyff/store.py
- src/pyff/utils.py
This PR allows to optionally pretty-print XML output.
> Pretty print

- src/pyff/samlmd.py
- src/pyff/test/data/metadata/test-sp.xml
Change the semantics of DisplayName's in non-strict TrustProfile elements: they are used to indicate why the functionality may be degraded using one of the non-selected IdPs.
> change semantics of the display names of trust profiles

- NEWS.txt
- src/pyff/constants.py
- src/pyff/samlmd.py
This adds a `discovery_responses` key in the JSON produced by discojson  for the SP entities that have DiscoveryResponse elements in their metadata.
This is to allow SeamlessAccess to warn users when they are sent to SeamlessAccess with a return URL that does not match the DiscoveryResponse elements published in the SP metadata.
> add DiscoveryResponse info to SPs in discojson

- src/pyff/constants.py
updated the config parameter of no_cashing to no_caching  
this may be a breaking change to some configs that have used this value
* [ x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ x ] Have you added an explanation of what problem you are trying to solve with this PR?
* [ x ] Have you added information on what your changes do and why you chose this as your solution?
* [ - ] Have you written new tests for your changes?
* [ x ] Does your submission pass tests?
* [ x ] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?
> Update constants.py to fix caching typo

- src/pyff/constants.py
trivial fix to a bug. for years the argument of -h has said that you can use -v or --version to print the version of pyFF - well, now you can
* [ x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ x ] Have you added an explanation of what problem you are trying to solve with this PR?
* [ x ] Have you added information on what your changes do and why you chose this as your solution?
* [ - ] Have you written new tests for your changes?
* [ x ] Does your submission pass tests?
* [ x] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?
> Update constants.py to allow -v to work

- NEWS.txt
- src/pyff/api.py
- src/pyff/builtins.py
- src/pyff/constants.py
- src/pyff/fetch.py
- src/pyff/logs.py
- src/pyff/samlmd.py
- src/pyff/test/data/metadata/test-sp-trustinfo-in-attr.xml
- src/pyff/test/data/metadata/test02-sp.xml
- src/pyff/test/test_pipeline.py
> Trust Info metadata in JSON blob in entity attribute

- src/pyff/i18n.py
- src/pyff/repo.py
This PR updates the last 1.x release containing an integrated discovery to be compatible with python 3.11, so it can be `pip installed` on a Debian Bookworm machine. This helps us deploying our test environment.
> Fixes for python 3.11
